version: '3'

services:
  mqtt-host:
    container_name: eclipse-mosquitto
    stdin_open: true
    restart: unless-stopped
    tty: true
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    image: eclipse-mosquitto

  heartbeat-client:
    container_name: heartbeat-client
    image: localhost/heartbeat-client
    build: .
    environment:
      MQTT_HOST: "mqtt-host"
    depends_on:
      - mqtt-host
    volumes:
      - './data:/app/data'
    command: './client/heartbeat.py'
